---
title: "Mappeoppgave 4"
output: pdf_document
  
 
  
---

**Laster ned de nødvendige pakkene:**
```{r setup, warning=FALSE, message=FALSE}
library(rvest)
library(tidyverse)
library(rlist)
```

- - - - 

**Lager en liste med de fagene som instruert i oppgaven:**
**Lager en funksjon med de trinnene som er gitt i mappeoppgave 4:** 
**Men gjør selve instruksen til om til en annerledes kode:** 
```{r warning=FALSE, message=FALSE }

url_liste <- 
  list("https://timeplan.uit.no/emne_timeplan.php?sem=22v&module%5B%5D=SOK-1005-1&week=4-20&View=list",
       "https://timeplan.uit.no/emne_timeplan.php?sem=22v&module[]=SOK-1006-1&week=4-20&View=list",
       "https://timeplan.uit.no/emne_timeplan.php?sem=22v&module%5B%5D=SOK-1016-1&week=4-20&View=list")

timeplan_rydd <- function(url) {
  side <- read_html(url)
  tabellen <- html_nodes(side, 'table') 
  tabellen <- html_table(tabellen, fill=TRUE) #Tvinger dem inn i en liste:
  listen <- list.stack(tabellen) #Stokker listene i et datasettet.
  colnames(listen) <- listen[1,] #Definerer første rad som variabel navn.
  listen <- listen %>% filter(!Dato=="Dato") #Fjerner rader med dato i seg
  listen <- listen %>% separate(Dato, 
                                into = c("Dag", "Dato"), 
                                sep = "(?<=[A-Za-z])(?=[0-9])") #Separer Dato i to kolonner
  listen <- listen[-length(listen$Dag),]
  listen$Dato <- as.Date(listen$Dato, format="%d.%m.%Y")
  listen$Uke <- strftime(listen$Dato, format = "%V")
  listen <- listen %>% select(Dag,Dato,Uke,Tid,Rom, Lærer, Emnekode)
  return(listen)
}

```

- - - - 

\newpage

**Legger sammen listene samtidig som dem blir ryddet ved hjelp av map-funksjonen:**
**Får da tre lister som innholder tre forskjellige fag**
```{r, message=FALSE, warning=FALSE}

timeplan <- map(url_liste, timeplan_rydd ) 

timeplan
```



